// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1T81b2rjUXu5fJx635sQ8RWbqfdXUbMQ',
    appId: '1:140179972997:web:3cd76f4caac95c544c5aec',
    messagingSenderId: '140179972997',
    projectId: 'mcas-companion',
    authDomain: 'mcas-companion.firebaseapp.com',
    storageBucket: 'mcas-companion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1T81b2rjUXu5fJx635sQ8RWbqfdXUbMQ',
    appId: '1:140179972997:android:3cd76f4caac95c544c5aec',
    messagingSenderId: '140179972997',
    projectId: 'mcas-companion',
    storageBucket: 'mcas-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T81b2rjUXu5fJx635sQ8RWbqfdXUbMQ',
    appId: '1:140179972997:ios:3cd76f4caac95c544c5aec',
    messagingSenderId: '140179972997',
    projectId: 'mcas-companion',
    storageBucket: 'mcas-companion.firebasestorage.app',
    iosBundleId: 'com.example.mcasCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1T81b2rjUXu5fJx635sQ8RWbqfdXUbMQ',
    appId: '1:140179972997:ios:3cd76f4caac95c544c5aec',
    messagingSenderId: '140179972997',
    projectId: 'mcas-companion',
    storageBucket: 'mcas-companion.firebasestorage.app',
    iosBundleId: 'com.example.mcasCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1T81b2rjUXu5fJx635sQ8RWbqfdXUbMQ',
    appId: '1:140179972997:web:3cd76f4caac95c544c5aec',
    messagingSenderId: '140179972997',
    projectId: 'mcas-companion',
    authDomain: 'mcas-companion.firebaseapp.com',
    storageBucket: 'mcas-companion.firebasestorage.app',
  );
}
